### ISSUE TITLE
How to contact you?

### ISSUE THREAD

**Issue by Anonymous0147** [0x3C50/0x3C50#1]
Hello how may I contact you?

**Comment by 0x3C50** [comment]
why

**Comment by Anonymous0147** [comment]
I need some guidance

**Comment by 0x3C50** [comment]
we can just do that here
what do you need help with

**Comment by Anonymous0147** [comment]
I need guidance on how to navigate my way around visual studio

**Comment by 0x3C50** [comment]
That's not an issue I can help with, I don't use visual studio
